export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const AUTHLOADING = 'AUTHLOADING';
export const PROCESSING = 'PROCESSING';
export const PROCESSENDED = 'PROCESSENDED';
export const LOGINUSER = 'LOGINUSER';
export const SETAUTOFILLINFO = 'SETAUTOFILLINFO';
export const CREATEACCOUNT = 'CREATEACCOUNT';
